[build]
  command = "npm install && node build.js"
  functions = "build/netlify/functions"
  publish = "build"

[functions]
  node_bundler = "esbuild"
  included_files = ["src/**/*", "public/**/*"]

[[redirects]]
  from = "/api/test"
  to = "/.netlify/functions/test-function"
  status = 200

[build.environment]
  NETLIFY = "true"
