[build]
  command = "npm install && npm run build"
  publish = "build"

[dev]
  command = "npm start"
  port = 3000

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/ssr"
  status = 200