[build]
  command = "npm install && node build.js"
  functions = "build/netlify/functions"
  publish = "build"

[functions]
  node_bundler = "esbuild"
  included_files = ["src/**/*", "utils/**/*"]

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/app"
  status = 200

[build.environment]
  NETLIFY = "true"