# To better understand this file read this:
# https://docs.ionos.space/docs/github-actions-customization/

name: "Deploy Now: Execute Build"

on:
  workflow_call:
    inputs:
      site-url:
        required: true
        type: string
      branch-id:
        required: true
        type: string

env:
  DEPLOYMENT_FOLDER: ./build

jobs:
# Please do not rename this job
  build-project:
    name: build IMBADEV
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build
        
      - name: Install production dependencies in build folder
        run: npm install --omit=dev --prefix build

      - name: Remove unnecessary files
        run: |
          find build/node_modules -type f \( -name "*.md" -o -name "*.ts" -o -name "*.map" \) -delete

      - name: Ensure .env file
        run: |
          echo "MONGODB_URI=${{ secrets.MONGODB_URI }}" > build/.env
          echo "SESSION_SECRET=${{ secrets.SESSION_SECRET }}" >> build/.env

      - name: Start the application
        run: node build/src/app.js
        continue-on-error: true

# Please do not touch the following action
      - name: Store deployment content
        uses: ionos-deploy-now/artifact-action@v1
        with:
          api-key: ${{ secrets.IONOS_API_KEY }}
          service-host: api-eu.ionos.space
          project-id: 02485442-d1ff-43f8-9c61-09a225579e25
          branch-id: ${{ inputs.branch-id }}
          version: ${{ github.sha }}
          folder: ${{ env.DEPLOYMENT_FOLDER }}
          config-file: .deploy-now/IMBADEV/config.yaml
          action: upload
