# To better understand this file read this:
# https://docs.ionos.space/docs/github-actions-customization/

name: "Deploy Now: Execute Build"

on:
  workflow_call:
    inputs:
      site-url:
        required: true
        type: string
      branch-id:
        required: true
        type: string

env:
  DEPLOYMENT_FOLDER: build
  IONOS_DEPLOYMENT_TEST: false  # You can change this to true when needed

jobs:
# Please do not rename this job
  build-project:
    name: build IMBADEV
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: v22.x

      - name: Build Node assets
        env:
          CI: true
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
          SITE_URL: ${{ inputs.site-url }}
          IONOS_DEPLOYMENT_TEST: ${{ env.IONOS_DEPLOYMENT_TEST }}
        run: |
          npm ci
          npm run build

      - name: Remove unnecessary files
        run: |
          find build/node_modules -type f \( -name "*.md" -o -name "*.ts" -o -name "*.map" \) -delete

      - name: Prepare for deployment
        run: |
          cp .deploy-now/IMBADEV/config.yaml build/
          cp package.json build/
          cp package-lock.json build/

# Please do not touch the following action
      - name: Store deployment content
        uses: ionos-deploy-now/artifact-action@v1
        with:
          api-key: ${{ secrets.IONOS_API_KEY }}
          service-host: api-eu.ionos.space
          project-id: e9b94db4-cd28-47d9-9b2c-e8a5e5da1392
          branch-id: ${{ inputs.branch-id }}
          version: ${{ github.sha }}
          folder: ${{ env.DEPLOYMENT_FOLDER }}
          config-file: .deploy-now/IMBADEV/config.yaml
          action: upload
